# -*- coding: utf-8 -*-
"""entity extraction.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xMw0PRgH9Kszlw2dF5V3E2RHK4HFLusK
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install ultralytics
import ultralytics
ultralytics.checks()
from ultralytics import YOLO
from PIL import Image

from google.colab import drive
drive.mount('/content/drive')

model = YOLO('/content/drive/MyDrive/Website Screenshots Dataset MIT/yolov8x.pt')
model = YOLO('/content/drive/MyDrive/Website Screenshots Dataset MIT/best (3).pt')
predictions=model.predict(source="aums.PNG",save=True)
display(Image.open('runs/detect/predict/aums.PNG'))
for result in predictions:
  a=result.boxes.xyxy #Tensor coordinates-all images
  b=result.names #class annot
print("num classes predicted", len(result.boxes))
image = Image.open("aums.PNG")
for i in range(len(result.boxes)):
  box = result.boxes[i]
  cords = box.xyxy[0].tolist()
  class_id = box.cls[0].item()
  conf = box.conf[0].item()
  print("Object type:", class_id)
  print("Class :", b[class_id])
  print("Coordinates:", cords)
  x_min, y_min, x_max, y_max = cords
  x_min, y_min, x_max, y_max = int(x_min), int(y_min), int(x_max), int(y_max)
  entity = image.crop((x_min, y_min, x_max, y_max))
  entity.save(f'entity_{i}.png')
  entity.show()